# Generated by Django 4.1.1 on 2022-10-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='fotos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero_identificacio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
            },
        ),
    ]
