# Generated by Django 4.1.1 on 2022-10-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='numero_identificacio',
            new_name='numero_identificacion',
        ),
    ]
