# Generated by Django 4.1.1 on 2022-10-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_rename_numero_identificacio_registro_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
